services:
  datascience-notebook:
    image: jupyter/datascience-notebook:python-3.10.9
    container_name: jupyter_name
    hostname: jupyter-mlops
    restart: always
    volumes:
      - ${PWD}/data/work:/home/insu:z
      - ${PWD}/data/requirements:/tmp:z
    ports:
      - "8888:8888"
    networks:
      - mlops_network
    environment:
      - NB_USER = insu
      - NB_UID=1000
      - NB_GID=100
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS='-R'
      - JUPYTER_ALLOW_INSECURE_WRITES=1

networks:
  mlops_network:
    name: mlops_network
    external: true

