name: Airflow CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Python 설정
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: 의존성 설치
      run: |
        python -m pip install --upgrade pip
        pip install apache-airflow
        pip install -r airflow/requirements.txt

    - name: Initialize Airflow Database
      run: |
        export AIRFLOW_HOME=$(pwd)/airflow_home
        mkdir -p $AIRFLOW_HOME
        airflow db init
        ls -la $AIRFLOW_HOME  # 디렉토리 내용 확인

    - name: Start Airflow Scheduler
      run: |
        export AIRFLOW_HOME=$(pwd)/airflow_home
        airflow scheduler &

    - name: DAG 테스트
      run: |
        export AIRFLOW_HOME=$(pwd)/airflow_home
        echo "Current directory: $(pwd)"
        echo "AIRFLOW_HOME: $AIRFLOW_HOME"
        ls -la $AIRFLOW_HOME  # 다시 한 번 디렉토리 내용 확인
        python -m unittest discover tests


    - name: 프로덕션 배포 (예시)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        echo "프로덕션 서버에 배포 중"
        # 여기에 배포 단계를 추가하세요

