name: Airflow CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      working-directory: "${{ github.workspace }}/airflow"
      AIRFLOW_HOME: "${{ github.workspace }}/airflow_home"
      AIRFLOW__CORE__DAGS_FOLDER: "${{ github.workspace }}/airflow/models/book_mlops"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: "SequentialExecutor"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "sqlite:///${{ github.workspace }}/airflow_home/airflow.db"
      PYTHONPATH: "${{ github.workspace }}/airflow"

    steps:
    - uses: actions/checkout@v4
    
    - name: Python 설정
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Print Folder Tree
      uses: jaywcjlove/github-action-folder-tree@main
      with:
       exclude: "node_modules|dist|.git|.husky"
       path: /home/runner/work/mlops-book/mlops-book
       depth: 100

    - name: 의존성 설치
      run: |
        python -m pip install --upgrade pip
        pip install apache-airflow
        pip install -r airflow/requirements.txt

    - name: Initialize Airflow Database
      run: |
        mkdir -p $AIRFLOW_HOME
        airflow db init
        ls -la $AIRFLOW_HOME  # 디렉토리 내용 확인

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=${{ github.workspace }}:${{ github.workspace }}/airflow:${{ github.workspace }}/airflow/models:${{ github.workspace }}/airflow/support" >> $GITHUB_ENV


    - name: Set Airflow Variables
      run: |
        airflow variables set AIRFLOW_DAGS_PATH $(pwd)/airflow/models

    - name: List DAGs
      run: |
       airflow dags list
       airflow dags report
       airflow dags list-import-errors

    - name: Start Airflow Scheduler
      run: |
        airflow scheduler &

    - name: DAG 테스트
      run: |
        echo "Current directory: $(pwd)"
        echo "AIRFLOW_HOME: $AIRFLOW_HOME"
        ls -la $AIRFLOW_HOME  # 다시 한 번 디렉토리 내용 확인
        python -m unittest discover tests

    - name: Trigger and Monitor DAG
      run: |
        airflow dags trigger book_mlops
        sleep 10  # DAG 실행을 기다림 (필요에 따라 조정)
        airflow tasks list book_mlops
        airflow dags list-runs --dag-id book_mlops --limit 5

    - name: 프로덕션 배포 (예시)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        echo "프로덕션 서버에 배포 중"
        # 여기에 배포 단계를 추가하세요

