name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    branches: [ main ]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs: ci
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: model-artifacts

    - name: Docker build and push
      uses: docker/build-push-action@v4
      with:
        context: ./deployment
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ github.sha }}

    - name: Deploy to Kubernetes
      uses: Azure/k8s-deploy@v4
      with:
        namespace: book-mlops
        manifests: deployment/manifests/
        images: |
          ghcr.io/${{ github.repository }}:${{ github.sha }}
