name: CI/CD for Book Recommendation Model

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -f airflow/Dockerfile -t book_mlops_model .
    
    # - name: Run tests
    #   run: |
    #     docker network create mlops_network || true
    #     docker run --rm --network=mlops_network book_mlops_model pytest

    - name: Push Docker image to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
        docker tag book_mlops_model ${{ secrets.DOCKER_USER }}/book_mlops_model:latest
        docker push ${{ secrets.DOCKER_USER }}/book_mlops_model:latest

    - name: Deploy to production (if applicable)
      run: |
        docker pull insu97/book_mlops_model:latest
        docker-compose -f production.yml up -d

