name: CI/CD for Book Recommendation Model

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.8.2
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: book_db
          MARIADB_USER: user
          MARIADB_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -uroot -proot" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -f airflow/Dockerfile -t book_mlops_model .

    - name: Wait for MariaDB
      run: |
        docker run --rm --network host mariadb:10.8.2 mysqladmin ping -h127.0.0.1 -uuser -ppassword --wait=30 --connect-timeout=20
    - name: Create Docker network
      run: docker network create mlops_network || true
      
    - name: Run tests
      run: |
        docker run --rm \
          --network mlops_network \
          -e AIRFLOW__CORE__DAGS_FOLDER=/app/airflow/models/book_mlops/ \
          -e AIRFLOW__CORE__LOAD_EXAMPLES=False \
          book_mlops_model pytest /app/airflow/models/book_mlops/main.py

    - name: Push Docker image to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
        docker tag book_mlops_model ${{ secrets.DOCKER_USER }}/book_mlops_model:latest
        docker push ${{ secrets.DOCKER_USER }}/book_mlops_model:latest

    - name: Deploy to production
      run: |
        docker pull ${{ secrets.DOCKER_USER }}/book_mlops_model:latest
        docker compose -f production.yml up -d
