name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AIRFLOW_HOME: ./airflow_home  # 환경 변수 상단으로 이동
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:///${{ github.workspace }}/test_airflow.db  # 절대 경로 사용
      AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: "False"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install -r airflow/requirements.txt
        pip install pytest
        
    - name: Initialize Airflow DB
      run: |
        airflow db init
        airflow variables set FEATURE_STORE_URL ${{ secrets.FEATURE_STORE_URL }}  # 테스트용 변수 주입

    - name: Run tests
      run: |
        pytest tests/ -v -s  # 상세 로그 출력 활성화

  train:
    needs: test
    runs-on: ubuntu-latest
    env:
      FEATURE_STORE_URL: ${{ secrets.FEATURE_STORE_URL }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Train model
      run: python -m models.book_recommend.train

    - name: Upload model artifacts
      uses: actions/upload-artifact@v3
      with:
        name: model-artifacts
        path: models/book_recommend/model/
