name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AIRFLOW_HOME: ./airflow_home
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:///${{ github.workspace }}/test_airflow.db
      AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: "False"
      AIRFLOW__CORE__DAGS_FOLDER: ${{ github.workspace }}/airflow/dags  # 절대 경로 지정

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install -r airflow/requirements.txt
        pip install pytest
        
    - name: Initialize Airflow DB
      run: |
        # 1. Airflow 설정 파일 강제 생성
        mkdir -p $AIRFLOW_HOME
        cat << EOF > $AIRFLOW_HOME/airflow.cfg
        [core]
        load_default_connections = False
        dags_folder = $AIRFLOW__CORE__DAGS_FOLDER
        
        [database]
        sql_alchemy_conn = $AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
        EOF
        
        # 2. DB 마이그레이션 실행
        airflow db migrate
        
        # 3. 기본 연결 정보 생성
        airflow connections create-default-connections

    - name: Run tests
      run: |
        pytest tests/ -v -s --log-cli-level=DEBUG

  train:
    needs: test
    runs-on: ubuntu-latest
    env:
      FEATURE_STORE_URL: ${{ secrets.FEATURE_STORE_URL }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install apache-airflow==2.7.3  # Airflow 버전 명시적 설치

    - name: Train model
      run: |
        mkdir -p $AIRFLOW_HOME
        python -m models.book_recommend.train

    - name: Upload model artifacts
      uses: actions/upload-artifact@v3
      with:
        name: model-artifacts
        path: models/book_recommend/model/
