name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AIRFLOW_HOME: ./airflow_home
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:///${{ github.workspace }}/test_airflow.db
      AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: "False"
      AIRFLOW__CORE__DAGS_FOLDER: ${{ github.workspace }}/airflow/dags  # 절대 경로 지정

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install -r airflow/requirements.txt
        pip install pytest
        
    - name: Initialize Airflow DB
      run: |
        # DAG 폴더 생성 및 샘플 DAG 추가
        mkdir -p ${{ github.workspace }}/airflow/dags
        echo 'from airflow import DAG; dag = DAG("test_dag")' > ${{ github.workspace }}/airflow/dags/test_dag.py
    
        # DB 초기화
        airflow db migrate
        airflow connections create-default-connections
    
        - name: Run tests
          run: |
            pytest tests/ -v -s --log-cli-level=DEBUG

  train:
    needs: test
    runs-on: ubuntu-latest
    env:
      FEATURE_STORE_URL: ${{ secrets.FEATURE_STORE_URL }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install apache-airflow==2.7.3  # Airflow 버전 명시적 설치

    - name: Train model
      run: |
        mkdir -p $AIRFLOW_HOME
        python -m models.book_recommend.train

    - name: Upload model artifacts
      uses: actions/upload-artifact@v3
      with:
        name: model-artifacts
        path: models/book_recommend/model/
