name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 모든 파일을 가져옴

    - name: Check files in workspace
      run: ls -la

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USER }}/book_mlops:latest .
      working-directory: .  # Dockerfile이 있는 디렉토리 설정

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USER }}/book_mlops:latest
